### ISSUE TITLE
aquaculture 2

### ISSUE THREAD

**Issue by foggirya000** [MrTroot/autofish#10]
Does not work with modded rods, just vanilla.

**Comment by aalexx-S** [comment]
Yeah, I'm having the same issue on 1.16. It looks like the only thing that may cause the issue is `isHoldingFishingRod()` check, but [the source code](https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/java/com/teammetallurgy/aquaculture/item/AquaFishingRodItem.java#L38) clearly shows that it is a type of `net.minecraft.item.FishingRodItem`.

**Comment by aalexx-S** [comment]
After some experimenting, I found out that it is a catch detection issue. After forcing multiplayer detection, it works perfectly. @MrTroot Can you update the documentation to inform users to try out force multiplayer detection if it's not workign with modded rods.

**Comment by troyhayes** [comment]
The multiplayer detection setting is the current workaround to get this working with modded rods. I believe newer versions signify that the checkbox is intended for mod compatibility.
